host= 'hostname'
report= 'report_path'
access= 'access_date'
up_time= 'upload_time'
bytes_send= 'bytes_send'
status= 'http_status_code'
agent= 'http_user_agent'
referer= 'http_referer'
cookie= 'cookie_ga'

